#!/bin/sh
#
# make CD-ROM disks of tar files from the RoadMap US files, one tar file
# per state.
#
MAPDIR=/usr/local/share/roadmap
TARDIR=/cdspace/roadmap


function tar1state {

   echo -n "$1  "

   tar cf - usc$2*.rdm | gzip -c -9 > $TARDIR/Disk$3/us$1.tar.gz
   (cd $TARDIR/Disk$3 ; ls -lh us$1.tar.gz)
}

rm -rf $TARDIR
mkdir -p $TARDIR/Disk1
mkdir -p $TARDIR/Disk2

cd $MAPDIR

tar1state AL 01 1
tar1state AK 02 2
tar1state AZ 04 1
tar1state AR 05 2
tar1state CA 06 1
tar1state CO 08 2
tar1state CT 09 1
tar1state DE 10 2
tar1state DC 11 1
tar1state FL 12 2
tar1state GA 13 1
tar1state HI 15 2
tar1state ID 16 1
tar1state IL 17 2
tar1state IN 18 1
tar1state IA 19 2
tar1state KS 20 1
tar1state KY 21 2
tar1state LA 22 1
tar1state ME 23 2
tar1state MD 24 1
tar1state MA 25 2
tar1state MI 26 1
tar1state MN 27 2
tar1state MS 28 1
tar1state MO 29 2
tar1state MT 30 1
tar1state NE 31 2
tar1state NV 32 1
tar1state NH 33 1
tar1state NJ 34 2
tar1state NM 35 1
tar1state NY 36 2
tar1state NC 37 1
tar1state ND 38 2
tar1state OH 39 1
tar1state OK 40 2
tar1state OR 41 1
tar1state PA 42 2
tar1state RI 44 1
tar1state SC 45 2
tar1state SD 46 1
tar1state TN 47 2
tar1state TX 48 1
tar1state UT 49 2
tar1state VT 50 1
tar1state VA 51 2
tar1state WA 53 1
tar1state WV 54 2
tar1state WI 55 1
tar1state WY 56 2
tar1state AS 60 1
tar1state GU 66 2
tar1state MP 69 1
tar1state PR 72 2
tar1state VI 78 1

cp usdir.rdm $TARDIR/Disk1
cp usdir.rdm $TARDIR/Disk2

