#!/bin/sh
#
# Usage:
#
#    mktarball <version>
#
# where <version> is either n.n[.n] or n_n[_n]
#

if [ "x$1" = "x" ] ; then
   echo "Version number is missing"
   exit 1
fi

version=`echo $1 | tr . _`
dotversion=`echo $1 | tr _ .`


PROJROOT=~/sourceforge

RELEASE=releases

RDM_SRC="roadmap/src/Makefile
         roadmap/src/app_a02.txt
         roadmap/src/usstates.txt
         roadmap/src/*.[ch]
         roadmap/src/gtk/Makefile
         roadmap/src/gtk/*.[ch]
         roadmap/src/gtk2/Makefile
         roadmap/src/gtk2/*.[ch]
         roadmap/src/qt/Makefile
         roadmap/src/qt/*.[ch]
         roadmap/src/qt/*.cc
         roadmap/src/qt/ipkg/zroad*
         roadmap/src/unix/Makefile
         roadmap/src/unix/*.[ch]
         roadmap/src/ipkg/mkipkg
         roadmap/src/ipkg/INSTALL
         roadmap/src/ipkg/roadmap*"

RDM_CFG="roadmap/src/preferences
         roadmap/src/schema
         roadmap/src/sprites
         roadmap/src/*.png
         roadmap/src/roadmap.desktop
         roadmap/src/roadmap.menu
         roadmap/src/icons/Makefile
         roadmap/src/icons/rm_*.xpm
         roadmap/src/icons/rm_*.png"

RDM_SH="roadmap/src/rdmdownload
        roadmap/src/rdmgetall
        roadmap/src/rdmgenmaps
        roadmap/src/rdmcompare"

RDM_BIN="roadmap/src/usdir.rdm
         roadmap/src/usc06075.rdm
         roadmap/src/gtk/gtkroadmap
         roadmap/src/gtk/gtkroadgps
         roadmap/src/gtk2/gtkroadmap
         roadmap/src/gtk2/gtkroadgps
         roadmap/src/qt/qtroadmap
         roadmap/src/qt/qtroadgps
         roadmap/src/buildmap
         roadmap/src/buildus"

RDM_DOC="roadmap/AUTHORS
         roadmap/BUGS
         roadmap/COPYING
         roadmap/README
         roadmap/TODO"

RDM_HELP="roadmap/web/manual.html roadmap/web/apt_toc.gif"

RDM_IPK="arm/roadmap/ipkg/roadmap_${dotversion}_arm.ipk"


cd $PROJROOT

mkdir -p $RELEASE

roadmap/src/ipkg/mkipkg $dotversion
echo "Done with ipkg"

rm -f roadmap/src/*.rdm
for i in usdir usc06075
do
   cp /usr/local/share/roadmap/$i.rdm roadmap/src
done

echo "Creating tar ball for section doc ..."
rm -f $RELEASE/roadmap_${version}_doc.tar*
cp roadmap/src/ipkg/INSTALL roadmap/INSTALL.familiar
aptconvert -toc roadmap/web/manual.html roadmap/README
aptconvert -toc roadmap/web/familiar.html roadmap/src/ipkg/INSTALL
tar cf $RELEASE/roadmap_${version}_doc.tar  $RDM_DOC roadmap/web roadmap/INSTALL.familiar
rm -f roadmap/INSTALL.familiar

echo "Creating tar ball for section src ..."
rm -f $RELEASE/roadmap_${version}_src.tar*
tar cf $RELEASE/roadmap_${version}_src.tar  $RDM_SRC $RDM_SH $RDM_CFG $RDM_DOC

echo "Creating tar ball for section i686 ..."
rm -f $RELEASE/roadmap_${version}_i686.tar*
tar cf $RELEASE/roadmap_${version}_i686.tar $RDM_BIN $RDM_SH $RDM_CFG $RDM_DOC $RDM_HELP

echo "Creating tar ball for section armv4l ..."
rm -f $RELEASE/roadmap_${version}_armv4l.tar*
rm -f roadmap/*.ipk
cp $RDM_IPK roadmap
cp roadmap/src/ipkg/INSTALL roadmap
tar cf $RELEASE/roadmap_${version}_armv4l.tar roadmap/*.ipk $RDM_DOC roadmap/INSTALL
rm -f roadmap/*.ipk roadmap/INSTALL

rm -f roadmap/src/*.rdm 


cd $RELEASE

for x in doc src i686 armv4l
do
  echo "Compressing tar ball for section $x ..."
  gzip -9 roadmap_${version}_$x.tar
done

