
# stub makefile -- sole purpose is to assist building tarball distributions

SOURCE = Makefile INSTALL mkipkg roadmap-build.control \
	roadmap-gtk2.control roadmap-sfca.control \
	roadmap.control roadmap.postinst roadmap.postrm

sourcelist:
	@echo $(SOURCE)

