
# stub makefile -- sole purpose is to assist building tarball distributions

SOURCE = Makefile agg_font_freetype.cpp agg_font_freetype.h \
	roadmap_canvas.cpp roadmap_canvas_agg.h

HEADERS = \
	agg_font_freetype.h \
	roadmap_canvas_agg.h

sourcelist:
	@echo $(SOURCE) $(HEADERS)

