#! /bin/sh
# postinst script for roadmap

set -e

case "$1" in
    configure)
        if [ -x /usr/bin/update-menus ] ; then update-menus ; fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
