.TH "roadgps" "1" "1.0.8" "Petter Reinholdtsen" ""
.SH "NAME"
.LP 
roadgps \- GPS status console
.SH "SYNTAX"
.LP 
roadgps
.SH "DESCRIPTION"
.LP 
A very handy GPS console, inspired by the Garmin satellite status
page, with a NMEA log capability.  Thanks to gpsd, roadgps and roadmap
can be active at the same time.
.SH "FILES"
.LP 
\fI~/.roadmap/preferences\fP 
.br 
\fI/etc/roadmap/preferences\fP 
.br 
\fI/usr/share/roadmap/preferences\fP 
.SH "AUTHORS"
.LP 
Pascal Martin <pascal.martin@ponts.org>
.LP 
This manual page was written by Petter Reinholdtsen for the Debian package.
.SH "SEE ALSO"
.LP 
gpsd(1) roadmap(1)
