#!/bin/sh
#
# rdmgenstatemaps
#
# Process the US state boundary map through buildmap.
#

usage()
{
    cat >&2 <<EOF
rdmgenstatemaps src=<path-to-st99-files> [maps=<map-directory-path>] [test]
  where the src=<> parameter points to a directory containing the unpacked
  contents of st99_d00_shp.zip, available from:
    http://www.census.gov/geo/cob/bdy/st/st00shp/st99_d00_shp.zip
EOF
   exit 1
}


# the state boundary map data is available from:
#
# http://www.census.gov/geo/www/cob/st2000.html
#
# specifically, 
# http://www.census.gov/geo/cob/bdy/st/st00shp/st99_d00_shp.zip
#

if [ $# -eq 0 ] ; then
    usage
fi

verbose=''
gendir=Y
DRYRUN=N

srcpath=.
case $1 in
    src=*) srcpath=`expr $1 : 'src=\(.*\)'`
            shift
            ;;
esac
file=$srcpath/st99_d00.shp

if [ ! -f $file ]
then
    echo $0: no such file $file >&2
    exit 1
fi

case $1 in
    maps=*) maps=`expr $1 : 'maps=\(.*\)'`
            shift
            ;;
esac

if [ ! -d $maps ]
then
    echo $0: no such directory $maps >&2
    exit 1
fi

case $1 in
    test) verbose=-v
          gendir=N
          shift
          ;;
esac

case $1 in
    dryrun) DRYRUN=Y
            shift
            ;;
esac

# default to free Road Network Format
shape=STATES

if [ ! "$BUILDMAP" ]
then
    if [ -e ./buildmap ] ; then
       BUILDMAP=./buildmap
    else
       BUILDMAP=buildmap
    fi
fi


FIPS=81001


echo $BUILDMAP -f STATES -m $maps $verbose $FIPS $file
if [ $DRYRUN != 'Y' ] ; then
    $BUILDMAP -f STATES -m $maps $verbose $FIPS $file
fi

if [ $gendir = 'Y' ] ; then
      
    echo "Generating usdir.rdm, please wait.."

    if [ ! "$BUILDUS" ]
    then
       if [ -e buildus ] ; then
          BUILDUS=./buildus
       else
          BUILDUS=buildus
       fi
    fi

    echo $BUILDUS -s --maps=$maps
    if [ $DRYRUN != 'Y' ] ; then
        $BUILDUS -s --maps=$maps
    fi
fi 
