
# stub makefile -- sole purpose is to assist building tarball distributions

# The home for the PHP sources for the osmgetbmap scripts is here:
#    https://svn.symbianos.org/osmtocsv/trunk
# and perhaps here:
#    https://svn.symbianos.org/osmtocsv/branches/pgf
#
# The copy in CVS for the RoadMap project may or may not be slightly
# different.

SOURCE = \
	osmgetbmap osmgetbmap.php osmgetbmapcore.php

sourcelist:
	@echo Makefile $(SOURCE)


depends:
